### ISSUE TITLE
Recording the Session?

### ISSUE THREAD

**Issue by jtmiller28** [Big-Bee-Network/name-alignment-workshop#11]
Are we going to be recording this session and posting it?

**Comment by jhpoelen** [comment]
@jtmiller28 good question! From previous experience I've learned that some folks records the presentations, but not the discussions. This is to help folks to share freely in discussions while also have a way to look at a recorded part of the presentation. 

I am sure that @seltmann also has ideas on this.

**Comment by jtmiller28** [comment]
Ask the audience if we can record. End at discussion component as Jorrit suggests
