### ISSUE TITLE
youtube.html missing from _includes

### ISSUE THREAD

**Issue by jhpoelen** [Big-Bee-Network/name-alignment-workshop#21]
@jtmiller28 any chance you have a youtube.html laying around? For some reason, I was unable the build the site because there's a missing youtube.html file - 

from https://github.com/Big-Bee-Network/name-alignment-workshop/actions/runs/3944032063/jobs/6749531661#step:4:209

```
[...]
  Rendering Markup: assets/css/lesson.scss
         Rendering: reference.md
  Pre-Render Hooks: reference.md
  Rendering Markup: reference.md
  Rendering Layout: reference.md
     Layout source: site
         Rendering: setup.md
  Pre-Render Hooks: setup.md
  Rendering Liquid: setup.md
github-pages 227 | Error:  Could not locate the included file 'youtube.html' in any of ["/github/workspace/_includes", "/usr/local/bundle/gems/jekyll-theme-primer-0.6.0/_includes"]. Ensure it exists in one of those directories and is not a symlink as those are not allowed in safe mode.
```

**Comment by jtmiller28** [comment]
@jhpoelen Removed embedded version of youtube.html. For some reason the direct link to the youtube.html path broke for the embedded version of the video. The backup direct link is still active, so I removed the embedded version to fix the build issue now.

**Comment by jtmiller28** [comment]
Also, unsure of how to troubleshoot this particular problem? I removed all instances of that html that I know of, however; the build still fails (but has been failing since initial commit in this repo). How did you obtain that specific fail step Error? Im only seeing the initial page 
![image](https://user-images.githubusercontent.com/82229873/213065346-829ce228-c399-4fc7-99d0-a00f3c232696.png)

**Comment by jhpoelen** [comment]
Reported issue was fixed, the error you saw is something else, I think.

**Comment by jhpoelen** [comment]
@jtmiller28 thanks for fixing, and looking forward to tomorrow.

**Comment by jtmiller28** [comment]
Sounds good! I’ll be adding the last few things we chatted about tomorrow
morning (was on flight all day today, now back in EST). Looking forward to
it!
