### ISSUE TITLE
add logos

### ISSUE THREAD

**Issue by seltmann** [Big-Bee-Network/name-alignment-workshop#22]
please add NSF logo, iDigBio, GloBI logo and Big Bee logo [https://github.com/Big-Bee-Network/logos](https://github.com/Big-Bee-Network/logos)

**Comment by jhpoelen** [comment]
https://github.com/globalbioticinteractions/logo

**Comment by jtmiller28** [comment]
Logos added to acknowledgments section. Recommendations for wording on the acknowledgments @seltmann @jhpoelen ? Currently:
A special thanks to the following organizations and projects that made this work and tutorial possible: NSF for their support and funding of Big-Bee, Extending Anthophila research through image and trait digitilization. (NSF:DBI:2102006), Global Biotic Interactions GLOBI for integration of Nomer for name alignment, and iDigBio for TCN support.

**Comment by jhpoelen** [comment]
Thanks for adding the logos. Looks pretty good to me!

**Comment by jtmiller28** [comment]
Closing issue as complete
