### ISSUE TITLE
Resizing images 

### ISSUE THREAD

**Issue by jtmiller28** [Big-Bee-Network/name-alignment-workshop#24]
Step-by-step images are currently blurry, removal of height and width arguments should increase resolution. Apply throughout and check on standard screen size.

**Comment by jtmiller28** [comment]
Images changed to width=100% , sizing looks better, however pngs are a bit fuzzy on my monitor. @jhpoelen any thoughts? May have to do with how I took the images initially, I screen clipped them -> transferred into inkscape -> exported as .png . Quality issue maybe? Export options during inkscape: 
![image](https://user-images.githubusercontent.com/82229873/221372134-6fa38210-13a5-4e6d-a3b8-dd89b1feab3c.png)

**Comment by jhpoelen** [comment]
@jtmiller28 thanks for the adjustments. Screenshots look pretty good in my browser (Brave Browser). The aspect ratio appears a little off, but I wonder whether it is worth the effort to retake the screenshots or tweak the aspect ratio somehow. I'd say call it done ; ) , but its all up to you. Perhaps @seltmann has some ideas on this.

**Comment by jtmiller28** [comment]
Closing issue for now, feel free to re-open if any of the visuals are not up to par
