### ISSUE TITLE
suggest to distribute/publish static html workshop package + recording

### ISSUE THREAD

**Issue by jhpoelen** [Big-Bee-Network/name-alignment-workshop#26]
Currently, the workshop is distributed via GitHub pages, and a github repository containing jekyll/markdown source files. 

Suggest to publish a package including the static html pages (e.g., compiled static website produced by Jekyll) as a Zenodo pub and include the mp4 recording also. 

Curious to hear thoughts of @jtmiller28  and @seltmann on this idea.

PS I'd be happy to put this together.

**Comment by jtmiller28** [comment]
I would agree that its a great idea. Maybe wait to publish it till more additions are implemented however, as I need to add the changes to the images to match the resolution of [issue 6](https://github.com/globalbioticinteractions/name-alignment-template/issues/6).

**Comment by seltmann** [comment]
@jtmiller28 @jhpoelen I think we should publish as soon as the issues are resolved.

**Comment by jtmiller28** [comment]
@jhpoelen, I noticed there is a major change to the output taxonomic table that outdates the current set up of the last page for the tutorial in terms of the table output. Any suggestions for updating this output? There is a lot of information now that would be challenging to capture in a screen shot, an option I can think of is pretrimming the table for fields of interest and focusing on those. 
[names-aligned.csv](https://github.com/Big-Bee-Network/name-alignment-workshop/files/11045461/names-aligned.csv)

**Comment by jhpoelen** [comment]
@jtmiller28 I've attempted to implement the changes suggested in the workshop. As we use the tool, I hope more folks come forward with additional ideas to make the output table more intuitive. I leave it up to you to update or keep the same. I think the narrative is the most important one. Perhaps include a little note saying that additional column may be added in future versions?

**Comment by jtmiller28** [comment]
@jhpoelen Understood. Due to probable changes in the future I left that note as suggested. Closing this issue as complete.
